language: python
python:
  - "3.8.10"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install pytest==6.2.4
  - pip install pytest-cov==2.12.1
script:
  - pytest

# Push the results back to codecov
after_success:
  - codecov
